#!/usr/bin/env bash
# Script that displays the content of the current directory in list format
# Only displays part of the name after first dash

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
